AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  devtales-gierkinet-database

  SAM Template for devtales-gierkinet-database

Parameters:
  Environment:
    Type: String
    Description: "The Product Environment eg. test/prod"
  Product:
    Type: String
    Description: Name of the Product

Resources:
  MainDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Product}-${Environment}-dynamodb-main
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
